name: Go Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  CGO_ENABLED: 1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Add dependcies for CGO
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install build-essential zip
          sudo apt-get -y install gcc-mingw-w64-x86-64
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Build (linux amd64)
        run: go build -a -o build/random_donate_linux_amd64 .
        env:
          GOOS: linux
          GOARCH: amd64
          CC: gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: random_donate_linux_amd64
          path: build/random_donate_linux_amd64

      - name: Build (linux arm64)
        run: go build -a -o build/random_donate_linux_arm64 .
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: random_donate_linux_arm64
          path: build/random_donate_linux_arm64

      - name: Build (linux arm)
        run: go build -a -o build/random_donate_linux_arm .
        env:
          GOOS: linux
          GOARCH: arm
          CC: arm-linux-gnueabihf-gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: random_donate_linux_arm
          path: build/random_donate_linux_arm

      - name: Build (windows amd64)
        run: go build -a -o build/random_donate_windows_amd64.exe .
        env:
          GOOS: windows
          GOARCH: amd64
          CC: x86_64-w64-mingw32-gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: random_donate_windows_amd64
          path: build/random_donate_windows_amd64.exe
